version: '3.8'
services:
  mysqldb:
    restart: always
    image: mysql:latest
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
    - dbmysql:/var/lib/mysql
  myapp:
    build:
      context: .
    command: ["bash", "./wait-for-it.sh", "mysqldb:3306", "--", "java", "-jar", "app.jar"]
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
volumes:
  dbmysql: